### PR TITLE
Added python3 compatibility

### PR DESCRIPTION
**Pull request by abhay447**
Edited capi/nspy_glue.c to modify function definitions for python3 at line 380.
Edited capi/nspy_glue.c to modify module initialization function at line 1301.
Edited import statements for all python modules in neuroshare folder to support python3.

### CODE REVIEW

**Comment by gicmo** [comment]
Hi! Thanks a lot for this pull request! Before this is merge-able, would you be so kind and clean up the history a bit, i.e. remove all the `back to original` commits, merge all travis related changes into one commit, remove commits that add and later delete test files, etc. Also get rid of the backup `.bkp` files.
I will look at the semantic changes meanwhile.

**Comment by abhay447** [comment]
Sorry I am still learning bit by bit about git. I have made the changes and let me know if further edits are required. :)

**Comment by gicmo** [comment]
I did some more git rebasing to get rid of some back-end-forth edits. Additionally I had to fix some usage of `range` etc in the codebase. It compiles with py 2 & 3 and `ns-convert` does work with an example file for both versions. But I want to change to code to always use the `PyCapsule` API.

**Comment by gicmo** [comment]
I have merge pr #14 which makes this one obsolete. Closing therefore. Thanks a lot @abhay447 for the work on this. Very, very much appreciated!!

**Comment by abhay447** [comment]
Thanks.   @gicmo.

**Pull request closed without merging**
